# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_mp25.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1134, 486)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(9, -1, -1, 7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAbrirFile = QtWidgets.QPushButton(self.frame_2)
        self.btnAbrirFile.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnAbrirFile.setFont(font)
        self.btnAbrirFile.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.btnAbrirFile.setObjectName("btnAbrirFile")
        self.horizontalLayout.addWidget(self.btnAbrirFile)
        self.txtArchivo = QtWidgets.QLineEdit(self.frame_2)
        self.txtArchivo.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtArchivo.setFont(font)
        self.txtArchivo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtArchivo.setObjectName("txtArchivo")
        self.horizontalLayout.addWidget(self.txtArchivo)
        self.btnEliminarDatos = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEliminarDatos.setFont(font)
        self.btnEliminarDatos.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.btnEliminarDatos.setObjectName("btnEliminarDatos")
        self.horizontalLayout.addWidget(self.btnEliminarDatos)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtTimeInterval = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtTimeInterval.setFont(font)
        self.txtTimeInterval.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtTimeInterval.setInputMask("")
        self.txtTimeInterval.setObjectName("txtTimeInterval")
        self.horizontalLayout.addWidget(self.txtTimeInterval)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.btnPromedio = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnPromedio.setFont(font)
        self.btnPromedio.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.btnPromedio.setObjectName("btnPromedio")
        self.horizontalLayout.addWidget(self.btnPromedio)
        self.btnDescargarFileExcel = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDescargarFileExcel.setFont(font)
        self.btnDescargarFileExcel.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btnDescargarFileExcel.setObjectName("btnDescargarFileExcel")
        self.horizontalLayout.addWidget(self.btnDescargarFileExcel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSalir = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSalir.setFont(font)
        self.btnSalir.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.btnSalir.setObjectName("btnSalir")
        self.horizontalLayout.addWidget(self.btnSalir)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(9, -1, -1, 9)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tblDatos = QtWidgets.QTableWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tblDatos.setFont(font)
        self.tblDatos.setStyleSheet("QWidget {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #aa00ff;\n"
"    padding: 2px;\n"
"\n"
"    border: 1px solid #fffff8;\n"
"    font-size: 8pt;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: #aa00ff;\n"
"    font-size: 8pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid #ff0000;\n"
"}")
        self.tblDatos.setObjectName("tblDatos")
        self.tblDatos.setColumnCount(0)
        self.tblDatos.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tblDatos)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.widget)
        self.frame_6.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableMeanTimeInterval = QtWidgets.QTableWidget(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableMeanTimeInterval.setFont(font)
        self.tableMeanTimeInterval.setStyleSheet("QWidget {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #c4c701;\n"
"    padding: 2px;\n"
"\n"
"    border: 1px solid #fffff8;\n"
"    font-size: 8pt;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: #c4c701;\n"
"    font-size: 8pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid #ff0000;\n"
"}")
        self.tableMeanTimeInterval.setObjectName("tableMeanTimeInterval")
        self.tableMeanTimeInterval.setColumnCount(0)
        self.tableMeanTimeInterval.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableMeanTimeInterval)
        self.tableCentralTendencyMeasures = QtWidgets.QTableWidget(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableCentralTendencyMeasures.setFont(font)
        self.tableCentralTendencyMeasures.setStyleSheet("QWidget {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #00ff7f;\n"
"    padding: 2px;\n"
"\n"
"    border: 1px solid #fffff8;\n"
"    font-size: 8pt;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: #00ff7f;\n"
"    font-size: 8pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid #ff0000;\n"
"}")
        self.tableCentralTendencyMeasures.setObjectName("tableCentralTendencyMeasures")
        self.tableCentralTendencyMeasures.setColumnCount(0)
        self.tableCentralTendencyMeasures.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableCentralTendencyMeasures)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 10)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frameGrafico = QtWidgets.QVBoxLayout()
        self.frameGrafico.setObjectName("frameGrafico")
        self.verticalLayout_2.addLayout(self.frameGrafico)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(2, 35)
        self.horizontalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 20)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 40)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.btnSalir.clicked.connect(mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "RqMe@n"))
        self.btnAbrirFile.setText(_translate("mainWindow", "Open File"))
        self.btnEliminarDatos.setText(_translate("mainWindow", "Clear Data and replace data for regression"))
        self.label.setText(_translate("mainWindow", "Time Interval"))
        self.label_2.setText(_translate("mainWindow", "seconds[S]-minute[T]-hour[H]-day[D]-week[W]-months[M]-year[Y]"))
        self.btnPromedio.setText(_translate("mainWindow", "Calculate Mean"))
        self.btnDescargarFileExcel.setText(_translate("mainWindow", "Download File"))
        self.btnSalir.setText(_translate("mainWindow", "Exit"))
