# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowDetectObject(object):
    def setupUi(self, MainWindowDetectObject):
        MainWindowDetectObject.setObjectName("MainWindowDetectObject")
        MainWindowDetectObject.resize(594, 475)
        self.centralwidget = QtWidgets.QWidget(MainWindowDetectObject)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblVideoCapture = QtWidgets.QLabel(self.frame_2)
        self.lblVideoCapture.setAlignment(QtCore.Qt.AlignCenter)
        self.lblVideoCapture.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblVideoCapture.setText("")
        self.lblVideoCapture.setObjectName("lblVideoCapture")
        self.horizontalLayout_3.addWidget(self.lblVideoCapture)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("border-color: rgb(85, 255, 255);\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnStart = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnStart.setFont(font)
        self.btnStart.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 255, 127);")
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_2.addWidget(self.btnStart)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnStop = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnStop.setFont(font)
        self.btnStop.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);")
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_2.addWidget(self.btnStop)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout.setStretch(0, 20)
        self.verticalLayout.setStretch(1, 5)
        self.horizontalLayout.addWidget(self.frame)
        MainWindowDetectObject.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowDetectObject)
        QtCore.QMetaObject.connectSlotsByName(MainWindowDetectObject)

    def retranslateUi(self, MainWindowDetectObject):
        _translate = QtCore.QCoreApplication.translate
        MainWindowDetectObject.setWindowTitle(_translate("MainWindowDetectObject", "Detect Object"))
        self.btnStart.setText(_translate("MainWindowDetectObject", "START"))
        self.btnStop.setText(_translate("MainWindowDetectObject", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowDetectObject = QtWidgets.QMainWindow()
    ui = Ui_MainWindowDetectObject()
    ui.setupUi(MainWindowDetectObject)
    MainWindowDetectObject.show()
    sys.exit(app.exec_())
